// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ZRLreeeoWWzNU9X6yXeN_YP0KRkU1LY',
    appId: '1:873489861892:android:edbf558b37d4b2dc7ed451',
    messagingSenderId: '873489861892',
    projectId: 'learn-loop-20e89',
    storageBucket: 'learn-loop-20e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYugMD-GbIJ-CCCpHUnz-H1aUrpI8EM4',
    appId: '1:873489861892:ios:83e2c39022b39f1d7ed451',
    messagingSenderId: '873489861892',
    projectId: 'learn-loop-20e89',
    storageBucket: 'learn-loop-20e89.firebasestorage.app',
    androidClientId: '873489861892-g8ta9ssf40q8h677nh75s4ailje8e3gk.apps.googleusercontent.com',
    iosClientId: '873489861892-9ogi831479t8nh9n9v8r1sqdrsbge8nt.apps.googleusercontent.com',
    iosBundleId: 'com.learnloop.learnLoopApp',
  );

}